# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - command: |
      echo "Done"
    name: Install Mojo
    # init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    before: |
      eval $(command gp env -e)
    init: |
      curl https://get.modular.com | MODULAR_AUTH=$MODULAR_AUTH sh -
      modular install mojo
      echo 'export MODULAR_HOME="/home/gitpod/.modular"' >> ~/.zshrc
      echo 'export PATH="/home/gitpod/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.zshrc
      source ~/.zshrc

#
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
